### ISSUE TITLE
Add admin_user_id to movements

### ISSUE THREAD

**Issue by dmitryrck** [dmitryrck/organize2#26]
* Add `admin_user_id` to `movements`.
* Whenever an outgo is created it should be the current user

**Comment by rafaelrpbelo** [comment]
## Questions
- Will Income have the same behavior?
- Are we going to display the admin user's info on the outgo details page?

**Comment by dmitryrck** [comment]
> ## Questions
> * Will Income have the same behavior?

Yep :)

> * Are we going to display the admin user's info on the outgo details page?

You mean show view? Yes.

My idea when I created this issue was to show who created the movement. This way if two (or more, of course) use the system it will be less confusing to wonder "who created this?" OR "I don't remember creating this one?".

cc @rafaelrpbelo

**Comment by dmitryrck** [comment]
Oh, I saw just now, I wrote `an outgo is created` in the description of the issue.

My bad :neutral_face:.
